spring:
  application:
    name: Go Lunch

springdoc:
  swagger-ui:
    csrf:
      enabled: true

logging:
  level:
    root: "info"

server:
  servlet:
    session:
      timeout: 30m

golunch:
  files:
    users: users.csv
  picker:
    wait-time: 10m
  webapp:
    static:
      dir: webapp/dist/webapp/browser/
