spring:
  application:
    name: Go Lunch

springdoc:
  swagger-ui:
    csrf:
      enabled: true

logging:
  level:
    root: "info"

server:
  servlet:
    session:
      timeout: 30m

picklunch:
  files:
    users: ${PL_USERS_FILE:users.csv}
  picker:
    wait-time: 10m
  webapp:
    static:
      dir: ${PL_WEBAPP_STATIC_DIR:webapp/dist/webapp/browser/}
