spring:
  jpa:
    properties.hibernate.format_sql: true

logging:
  level:
    golunch: "debug"
    org.springframework.security: "debug"
    org.springframework.web: "debug"
    org.hibernate: "debug"
