spring:
  application:
    name: Pick Lunch

springdoc:
  swagger-ui:
    csrf:
      enabled: true

logging:
  level:
    root: "info"

server:
  servlet:
    session:
      timeout: 30m

picklunch:
  files:
    users: ${PL_USERS_FILE:users.csv}
  picker:
    wait-time: ${PL_WAIT_TIME:10m}
  webapp:
    static:
      dir: ${PL_WEBAPP_STATIC_DIR:webapp/dist/webapp/browser/}
