spring:
  application:
    name: Pick Lunch

springdoc:
  swagger-ui:
    csrf:
      enabled: true

logging:
  level:
    root: "info"

server:
  servlet:
    session:
      timeout: 30m

picklunch:
  files:
    users: ${PICKLUNCH_USERS_FILE:users.csv}
  picker:
    wait-time: ${PICKLUNCH_PICKER_WAITTIME:10m}
  webapp:
    static:
      dir: ${PICKLUNCH_WEBAPP_STATIC_DIR:webapp/dist/webapp/browser/}
